name: iOS CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - "/android/**"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "/android/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
      working-directory: ./example
    - run: touch assets/tomtom.txt
      working-directory: ./example
    - run: wget https://github.com/maplibre/maplibre-native/releases/download/ios-v5.13.0/Mapbox-5.13.0.zip
      working-directory: ./example/ios
    - run: unzip Mapbox-5.13.0.zip
      working-directory: ./example/ios
    - run: mv Mapbox.xcframework/ios-arm64/Mapbox.framework .
      working-directory: ./example/ios
    - run: flutter build ios --release --no-codesign
      working-directory: ./example
